#pragma once

using namespace ATL;

template <class T>
class CProxy_IDropTEvents : public IConnectionPointImpl<T, &__uuidof(_IDropTEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
